### PR TITLE
University theses

### PR DESCRIPTION
**Pull request by CSMathematics**
Master Thesis in Mathematics - University of Ioannina - Greece

### CODE REVIEW

**Comment by sunderme** [comment]
For multi-file templates to work, they need to be placed in a zip file.
Also description is missing, see:
[manual](https://texstudio-org.github.io/background.html#the-document-template-format)
and [example](https://github.com/texstudio-org/texstudio/tree/master/templates) template_Book.(json/png/zip)

**Comment by CSMathematics** [comment]
I see what you mean. I will work on that.

**Comment by CSMathematics** [comment]
I think the templates are ok now.

**Comment by CSMathematics** [comment]
Would it be helpul if the folder structure is like this:

--University templates
&emsp;&emsp;&emsp;|____ Country
&emsp;&emsp;&emsp;&emsp;&emsp;|_____ Name of university
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;|_____ BSc template
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;|_____ MSc Template
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;|_____ Phd Template
At least for university templates?

**Comment by sunderme** [comment]
I don't see the need to have sub-directories for Msc/Bsc
Txs will only show the summary from the json files, so the user will just see BSc/MSc templates without the additional (internal) files

For now, "University Template/Name of university" and then all files in that folder seems sufficient.

**Comment by sunderme** [comment]
multi-file definition json-files should have the line:
`"FilesToOpen" : "main.tex"`  (here open main.tex)

**Comment by CSMathematics** [comment]
I think the templates are ok now.

- The folder structure is simplified
- I added the line "FolderToOpen" in both MSc and Phd templates
- I tested both templates in Txs on my computer and they work.

**Comment by sunderme** [comment]
thanks

**Pull request merged**
