### PR TITLE
Added template for computer science research papers

### PR DESCRIPTION
**Pull request by HaririAli**
This is a style-agnostic template that eliminates the need to write style-specific code and eases switching between the typical document classes of computer science research papers. It supports IEEEtran, llncs and acmart styles, so users can switch between these styles by changing a single macro only. The tex code will automatically take care of everything else.

### CODE REVIEW

**Comment by sunderme** [comment]
unfortunatley your PR is not working.
If you want to handle more than one tex files (and additional files), you need to pack it into a zip file.
Example: https://github.com/texstudio-org/texstudio/tree/master/templates template_Book.json/png/zip
Currently the zip does not work from online repository, but if you provide the template, I will adapt txs.

**Comment by HaririAli** [comment]
I have updated the PR with a zip file as requested 👍

**Comment by sunderme** [comment]
okay, I will check it with txs then and adapt txs if necessary.

**Comment by sunderme** [comment]
thanks

**Pull request merged**
